### PR TITLE
Fixes due to releasing doxygenize v1.2

### PR DESCRIPTION
**Pull request by langroodi**
In this merge request, the latest auto commit by the doxygenize action is reverted. There was two errors in the Doxygen config file which were using absolute local directory paths. Besides that the dot tool for Doxygen is disabled, because the Apline docker of the action does not support it yet.

You can check the Doxygen output via this link (will be deleted after the changes are merged):
https://langroodi.github.io/tareaSD

### CODE REVIEW

**Comment by MatiasLGonzalez** [comment]
Thank you for taking your time to solve this, I hope the repo was useful to you, your effort is greatly appreciated, this is a really cool action!

Thanks for the heads up on the absolute path bugs, it was also my first time using the doxywizard app, I guess the app is using absolute path since it asks you to select a folder from a directory selection pop up screen.

> Besides that the dot tool for Doxygen is disabled, because the Apline docker of the action does not support it yet.

Do you think you may add graphviz in the future? [Someone](https://github.com/noahwilliamsson/docker-graphviz/blob/graphviz-update/Dockerfile) added it to the Alpine docker image in the past it would seem. Might be worth taking a look 🙂

**Comment by langroodi** [comment]
Thanks also for reporting the bugs with clear materials, so I was able to fix them with less effort ;)

> Do you think you may add graphviz in the future? [Someone](https://github.com/noahwilliamsson/docker-graphviz/blob/graphviz-update/Dockerfile) added it to the Alpine docker image in the past it would seem. Might be worth taking a look slightly_smiling_face

 I hope so, if I find a bit more time slot besides working on main repo (and I need to upload 3 more repos as well). I guess it should not be that much hassle to add it, the only issue is that the action chain will rely on more dependencies (which is not the aim of this action). I also appreciate if someone contribute to the repo and add it :)

**Comment by MatiasLGonzalez** [comment]
@langroodi I added graphviz to the docker file of my [fork](https://github.com/MatiasLGonzalez/doxygenize/blob/master/Dockerfile) of doxygenize. As far as I can tell it is making the [graphs](https://matiaslgonzalez.github.io/tareaSD/main_8c.html) correctly and there are no warning/errors about it, though I'm no docker expert

```
Build container for action use: '/home/runner/work/_actions/MatiasLGonzalez/doxygenize/2078b32e0b8bf46e013cf141776bed9df2ac880b/Dockerfile'.
  /usr/bin/docker build -t e1cc51:3cba2dc02368469ba2b678afa07b0138 -f "/home/runner/work/_actions/MatiasLGonzalez/doxygenize/2078b32e0b8bf46e013cf141776bed9df2ac880b/Dockerfile" "/home/runner/work/_actions/MatiasLGonzalez/doxygenize/2078b32e0b8bf46e013cf141776bed9df2ac880b"
  Sending build context to Docker daemon  118.8kB
  
  Step 1/8 : FROM alpine:3.14.2
  3.14.2: Pulling from library/alpine
  Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
  Status: Downloaded newer image for alpine:3.14.2
   ---> 14119a10abf4
  Step 2/8 : RUN ls
   ---> Running in 00bbd3c20941
  bin
  dev
  etc
  home
  lib
  media
  mnt
  opt
  proc
  root
  run
  sbin
  srv
  sys
  tmp
  usr
  var
  Removing intermediate container 00bbd3c20941
   ---> 2f801a444781
  Step 3/8 : WORKDIR /graphviz
   ---> Running in b156e9c65712
  Removing intermediate container b156e9c65712
   ---> 90734ad8eff6
  Step 4/8 : RUN apk add --update --no-cache            graphviz            ttf-freefont
   ---> Running in 5addc580be36
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
  (1/42) Installing libxau (1.0.9-r0)
  (2/42) Installing libmd (1.0.3-r0)
  (3/42) Installing libbsd (0.11.3-r0)
  (4/42) Installing libxdmcp (1.1.3-r0)
  (5/42) Installing libxcb (1.14-r2)
  (6/42) Installing libx11 (1.7.2-r0)
  (7/42) Installing libxext (1.3.4-r0)
  (8/42) Installing libice (1.0.10-r0)
  (9/42) Installing libuuid (2.37-r0)
  (10/42) Installing libsm (1.2.3-r0)
  (11/42) Installing libxt (1.2.1-r0)
  (12/42) Installing libxmu (1.1.3-r0)
  (13/42) Installing libxpm (3.5.13-r0)
  (14/42) Installing libxaw (1.0.14-r0)
  (15/42) Installing libxrender (0.9.10-r3)
  (16/42) Installing expat (2.4.1-r0)
  (17/42) Installing brotli-libs (1.0.9-r5)
  (18/42) Installing libbz2 (1.0.8-r1)
  (19/42) Installing libpng (1.6.37-r1)
  (20/42) Installing freetype (2.10.4-r1)
  (21/42) Installing fontconfig (2.13.1-r4)
  (22/42) Installing pixman (0.40.0-r2)
  (23/42) Installing cairo (1.16.0-r3)
  (24/42) Installing libgcc (10.3.1_git20210424-r2)
  (25/42) Installing libffi (3.3-r2)
  (26/42) Installing libintl (0.21-r0)
  (27/42) Installing libblkid (2.37-r0)
  (28/42) Installing libmount (2.37-r0)
  (29/42) Installing pcre (8.44-r0)
  (30/42) Installing glib (2.68.3-r0)
  (31/42) Installing libltdl (2.4.6-r7)
  (32/42) Installing libxft (2.3.3-r0)
  (33/42) Installing fribidi (1.0.10-r0)
  (34/42) Installing graphite2 (1.3.14-r0)
  (35/42) Installing harfbuzz (2.8.1-r0)
  (36/42) Installing pango (1.48.5-r0)
  (37/42) Installing libstdc++ (10.3.1_git20210424-r2)
  (38/42) Installing graphviz (2.47.1-r0)
  (39/42) Installing encodings (1.0.5-r0)
  (40/42) Installing libfontenc (1.1.4-r0)
  (41/42) Installing mkfontscale (1.2.1-r1)
  (42/42) Installing ttf-freefont (20120503-r1)
  Executing busybox-1.33.1-r3.trigger
  Executing fontconfig-2.13.1-r4.trigger
  Executing graphviz-2.47.1-r0.trigger
  Executing mkfontscale-1.2.1-r1.trigger
  OK: 40 MiB in 56 packages
  Removing intermediate container 5addc580be36
   ---> 4e9e5fbe110e
  Step 5/8 : WORKDIR -
   ---> Running in 5198c92fef05
  Removing intermediate container 5198c92fef05
   ---> af1b61a99795
  Step 6/8 : RUN ls
   ---> Running in 45b0b734e708
  Removing intermediate container 45b0b734e708
   ---> 516a3b6ea511
  Step 7/8 : COPY entrypoint.sh /entrypoint.sh
   ---> cf987c5e5d10
  Step 8/8 : ENTRYPOINT ["sh", "/entrypoint.sh"]
   ---> Running in 9221d7aef387
  Removing intermediate container 9221d7aef387
   ---> 863611467390
  Successfully built 863611467390
  Successfully tagged e1cc51:3cba2dc02368469ba2b678afa07b0138
```

My concern is if something might break because I change the workdir just like the [docker-graphviz](https://github.com/noahwilliamsson/docker-graphviz/blob/0fbfe20a1ca75cbc64c99cfd43c553fe1c98c2ba/Dockerfile) does, let me know if it works for you I'll clean it up and create the PR

**Comment by langroodi** [comment]
That is nice effort. Good job. At the first glance it looks fine. I will take a deeper look this week and let you know ;)

**Pull request merged**
